language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test_xunit
  - make docker_build
  - make docker_push
deploy:
    provider: heroku
    app: ancient-journey-30490
    api_key: ${HEROKU_API_KEY}
    
